[package]
name = "dissat"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1.35", features = ["max_level_trace", "release_max_level_off"] }

[dev-dependencies]
datatest = "0.7.1"
tracing-subscriber = "0.3.14"

[features]
